name: Metrics
on:
  # Обновлять каждые 24 часа
  schedule: [{cron: "0 0 * * *"}]
  # Возможность запускать вручную
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Базовые метрики
          base: header, activity, community, repositories, metadata
          
          # Настройки
          config_timezone: Europe/Moscow
          config_padding: 0, 8 + 11%
          
          # Стилизация через CSS (Исправлено)
          extras_css: |
            svg { background-color: #0D1117; border-radius: 10px; }
            .field { color: #61DAFB; }
            h1, h2, h3 { color: #61DAFB; }
