name: Metrics
on:
  # Обновлять каждые 24 часа
  schedule: [{cron: "0 0 * * *"}]
  # Возможность запускать вручную
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Твой никнейм
          user: vilzar
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Настройки внешнего вида
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Moscow
          
          # Цвета (Темная тема React)
          config_style: |
            body { background-color: #0D1117 !important; }
            h1, h2, h3 { color: #61DAFB !important; }
